export const NIFTY_SERIES_FETCH_REQUEST = 'NIFTY_SERIES/FETCH_REQUEST';
export const NIFTY_SERIES_FETCH_SUCCESS = 'NIFTY_SERIES/FETCH_SUCCESS';
export const NIFTY_SERIES_FETCH_FAILURE = 'NIFTY_SERIES/FETCH_FAILURE';

export const NIFTY_SERIES_RESET_STATE = 'NIFTY_SERIES/RESET_STATE';

