export const OPTION_CHAIN_POLL_REQUEST = 'OPTION_CHAIN/POLL_REQUEST';
export const OPTION_CHAIN_POLL_SUCCESS = 'OPTION_CHAIN/POLL_SUCCESS';
export const OPTION_CHAIN_POLL_FAILURE = 'OPTION_CHAIN/POLL_FAILURE';

