export const NIFTY_POLL_REQUEST = 'NIFTY/POLL_REQUEST';
export const NIFTY_POLL_SUCCESS = 'NIFTY/POLL_SUCCESS';
export const NIFTY_POLL_FAILURE = 'NIFTY/POLL_FAILURE';

export const NIFTY_START_POLLING = 'NIFTY/START_POLLING';
export const NIFTY_STOP_POLLING = 'NIFTY/STOP_POLLING';

