// Action type constants for auth feature
export const AUTH_SEND_OTP_REQUEST = 'AUTH/SEND_OTP_REQUEST';
export const AUTH_SEND_OTP_SUCCESS = 'AUTH/SEND_OTP_SUCCESS';
export const AUTH_SEND_OTP_FAILURE = 'AUTH/SEND_OTP_FAILURE';

export const AUTH_VERIFY_OTP_REQUEST = 'AUTH/VERIFY_OTP_REQUEST';
export const AUTH_VERIFY_OTP_SUCCESS = 'AUTH/VERIFY_OTP_SUCCESS';
export const AUTH_VERIFY_OTP_FAILURE = 'AUTH/VERIFY_OTP_FAILURE';

export const AUTH_REFRESH_TOKEN_REQUEST = 'AUTH/REFRESH_TOKEN_REQUEST';
export const AUTH_REFRESH_TOKEN_SUCCESS = 'AUTH/REFRESH_TOKEN_SUCCESS';
export const AUTH_REFRESH_TOKEN_FAILURE = 'AUTH/REFRESH_TOKEN_FAILURE';

export const AUTH_USER_STATUS_SUCCESS = 'AUTH/USER_STATUS_SUCCESS';

export const AUTH_RESET_STATE = 'AUTH/RESET_STATE';
export const AUTH_LOGOUT = 'AUTH/LOGOUT';

